---
functional:
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность добавлять товары в корзину и
    просматривать содержимое корзины
  - Пользователь должен иметь возможность искать товары по ключевому слову или
    категории
  - На странице корзины пользователь может удалить товар из корзины, продолжить
    выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты.
  - Можно добавлять товар в корзину и продолжать выбор товаров
  - На странице товара и в каталоге отображается название, рейтинг, цена со
    скидкой и без нее
non-functional:
  - Сайт должен иметь мобильную версию
  - Сайт должен быть доступен на различных устройствах
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - SPA
  - Сайт должен быть безопасным и защищать данные пользователя
  - Корзина будет хранится в сессии браузера
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для
    скорости работы
implicit:
  - Должно отображаться модальное окно при успешном добавлении товара в корзину,
    а так же при его удалении из корзины
  - Реализована возможность возвращения на первую страницу после просмотра
    товаров
  - После оформления заказа должно выводится окно с подтверждением успешного
    оформления заказа
  - После успешного оформления заказа, товар должен удалятся из корзины
  - На странице выбора товаров пользователь может сортировать список товаров.
    (По убыванию и возрастанию цены, рейтингу товара а так же по размеру скидки
    на товар)
